# -*- coding: utf-8 -*-
"""Caesar Cipher.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qz8R0T7GxyJ2wsw_eFct6K5yxVu6rbIS

### **Text Encryption Using Caesar Cipher Algorithm**

---
"""

def caesar_cipher_encrypt(text, shift):
    encrypted_text = ""

    for char in text:
        if char.isalpha():  # Check if the character is a letter
            # Determine whether the letter is uppercase or lowercase
            is_upper = char.isupper()

            # Shift the letter and wrap around the alphabet
            char_code = ord(char) + shift
            if is_upper:
                if char_code > ord('Z'):
                    char_code -= 26

            else:
                if char_code > ord('z'):
                    char_code -= 26

            encrypted_char = chr(char_code)
            encrypted_text += encrypted_char
        else:
            # If the character is not a letter, keep it unchanged
            encrypted_text += char

    return encrypted_text

# Get user input
plaintext = input("Enter the text to encrypt: ")
shift_amount = int(input("Enter the shift amount (integer): "))

# Encrypt the input using the Caesar cipher
encrypted_text = caesar_cipher_encrypt(plaintext, shift_amount)

# Display the encrypted text
print("Encrypted Text:", encrypted_text)